name: Publish workflow

on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@1.3.1
        with:
          credential: ${{ secrets.PUB_CREDENTIALS }}